-- Smart Store Agent v3.1 - Supabase DB Schema
-- Gemini Step 3 지침에 따른 스키마

-- 1. 시장 분석 요청 테이블 (분석 이력 관리)
CREATE TABLE market_analysis_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT NOT NULL,
    category TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'pending' -- pending, processing, completed, failed
);

-- 2. 분석 결과 상세 테이블 (JSONB 활용으로 유연성 확보)
CREATE TABLE analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT REFERENCES market_analysis_requests(id),
    keyword TEXT NOT NULL,

    -- 마진 분석 결과 (v3.1 핵심 데이터)
    margin_data JSONB,
    -- 예: {"margin_rate": -28.0, "total_cost": 57582, "is_viable": false}

    -- AI 분석 결과
    ai_analysis JSONB,
    -- 예: {"complaints": [...], "copywriting": [...], "spec_checklist": [...]}

    -- 최종 리포트 (Markdown 원본)
    report_content TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RLS (Row Level Security) 설정 (선택사항: 멀 연동 시 필요)
ALTER TABLE market_analysis_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_results ENABLE ROW LEVEL SECURITY;

-- 일단 개발 편의를 위해 모든 접근 허용 (배포 시 수정 필요)
CREATE POLICY "Allow all access" ON market_analysis_requests FOR ALL USING (true);
CREATE POLICY "Allow all access" ON analysis_results FOR ALL USING (true);

-- 4. 인덱스 (성능 최적화)
CREATE INDEX idx_requests_keyword ON market_analysis_requests(keyword);
CREATE INDEX idx_requests_status ON market_analysis_requests(status);
CREATE INDEX idx_results_keyword ON analysis_results(keyword);
CREATE INDEX idx_results_request_id ON analysis_results(request_id);

-- 5. 키워드 데이터 테이블 (선택: 아이템스카우트 데이터 저장용)
CREATE TABLE keyword_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT NOT NULL,
    monthly_search_volume INT,
    monthly_search_volume_pc INT,
    monthly_search_volume_mobile INT,
    total_products INT,
    competition_rate DECIMAL(10, 4),
    avg_price INT,
    opportunity_score DECIMAL(10, 2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_keyword_data_keyword ON keyword_data(keyword);
CREATE INDEX idx_keyword_data_opportunity ON keyword_data(opportunity_score DESC);

-- 6. 상품 스펙 테이블 (선택: 스펙 검증용)
CREATE TABLE product_specs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT,
    weight_kg DECIMAL(10, 3),
    dimensions_cm JSONB, -- {"length": 80, "width": 20, "height": 15}
    max_load_kg DECIMAL(10, 2),
    material TEXT,
    waterproof_rating TEXT,
    certifications JSONB, -- ["KC", "CE"]
    extra_specs JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 리뷰 분석 결과 테이블 (선택: 리뷰 분석 결과 저장)
CREATE TABLE review_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT NOT NULL,
    total_reviews INT,
    complaint_reviews INT,
    positive_reviews INT,
    neutral_reviews INT,
    top_complaints JSONB, -- [{"category": "품질", "count": 15}, ...]
    complaint_keywords JSONB, -- {"품질 별로": 5, "냄새": 3}
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 완료 메시지
-- 실행 후 Supabase Dashboard에서 테이블 생성 확인
